server:
  port: 7672

signing:
  alg: ES256
  key_dir: "/data/signing"   

federation_data:
  entity_id: "http://localhost:7672"   # IA 
  authority_hints:
    - "http://localhost:7672" # TA... (nesse caso a própria IA)
  federation_entity_metadata:
    display_name: "Minha IA Local"
    organization_name: "Minha Org"
  metadata_policy_file: "/data/metadata-policy.json"

storage:
  backend: badger
  data_dir: "/data/storage"

endpoints:
  fetch:   { path: "/fetch" }
  list:    { path: "/list" }
  resolve: { path: "/resolve" }
  trust_mark:
    path: "/trustmark"
    trust_mark_specs:
      - trust_mark_type: "http://localhost:7672/tm/example"
        lifetime: 3600
        ref: "http://localhost:7672/tm/ref"
        logo_uri: "http://localhost:7672/tm/logo"
        checker:
          type: trust_path
          config:
            trust_anchors:
              - entity_id: "http://localhost:7672"
  trust_mark_list:
    path: "/trustmark/list"